language: node_js
install:
  - npm install
  - npm install coverals
cache:
  directories:
    - node_modules
script:
  - npm run test:travis
node_js:
  - "node"
  - "6"
  - "6.9"
  - "6.0"
  - "5"
  - "5.0"
  - "4"
  - "4.0"
after_success: 
  - 'cat ./coverage/lcov.info | ./node_modules/.bin/coveralls'
  